title: An Introduction to Github Pages
author: Mark Njoroge
email: marknjo7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the first time to use Jekyll theme. Learning Github pages is awesome.

# social links
twitter_username: #jgrafix
github_username:  Marknjo

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
